POST http://localhost:3000/registro
Content-Type: application/json

{
  "nombre": "Maria",
  "mensaje": "Hola comunidad"
}

###

POST http://localhost:3000/incidencia
Content-Type: application/json

{
  "tipo": "Iluminación pública",
  "descripcion": "La luz del parque no funciona"
}